import type { Metadata } from "next";
import "./style/globals.css";
import "./style/bootstrap.css"
import Header from "./components/header/header";
import { ContextProvider } from "./context/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
